"""Add design, category, and fabric tables

Revision ID: ec834153fa8e
Revises: 7dcaee9ea011
Create Date: 2025-11-09 16:50:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "ec834153fa8e"
down_revision: Union[str, Sequence[str], None] = "7dcaee9ea011"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create categories table
    op.create_table(
        "categories",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_categories_name"), "categories", ["name"], unique=False)
    
    # Create fabrics table
    op.create_table(
        "fabrics",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("image_url", sa.String(), nullable=True),
        sa.Column("price_per_meter", sa.Float(), nullable=True),
        sa.Column("category_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_fabrics_name"), "fabrics", ["name"], unique=False)
    
    # Create designs table
    op.create_table(
        "designs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("category_id", sa.UUID(), nullable=False),
        sa.Column("fabric_id", sa.UUID(), nullable=False),
        sa.Column("customization", postgresql.JSONB(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["fabric_id"],
            ["fabrics.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_designs_name"), "designs", ["name"], unique=False)
    op.create_index(op.f("ix_designs_user_id"), "designs", ["user_id"], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop designs table
    op.drop_index(op.f("ix_designs_user_id"), table_name="designs")
    op.drop_index(op.f("ix_designs_name"), table_name="designs")
    op.drop_table("designs")
    
    # Drop fabrics table
    op.drop_index(op.f("ix_fabrics_name"), table_name="fabrics")
    op.drop_table("fabrics")
    
    # Drop categories table
    op.drop_index(op.f("ix_categories_name"), table_name="categories")
    op.drop_table("categories")
    
    # ### end Alembic commands ###
